import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "../components/NavBar";
import React, { useState } from "react";
import Footer from "../components/Footer";
import { Analytics } from "@vercel/analytics/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LocaleLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale };
}) {
  return (
    <html lang={locale}>
      <body className={inter.className}>
        <NavBar />
        <main className="font-robotoFlex">{children}</main>
        <Footer />
        <Analytics />
      </body>
    </html>
  );
}
