import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import React, { useState } from "react";
import Footer from "./components/Footer";
import { Analytics } from "@vercel/analytics/react";
import { i18n, type Locale } from "../../src/i18nConfig";

const inter = Inter({ subsets: ["latin"] });

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: Locale };
}) {
  return (
    <html lang={params.lang}>
      <body className={inter.className}>
        <NavBar params={params.lang} />
        <main className="font-robotoFlex">{children}</main>
        <Footer />
        <Analytics />
      </body>
    </html>
  );
}
